#!/usr/bin/env python3
"""
Dynamic Nginx Configuration API using Python standard library.
Provides REST API to manage backend routes and triggers graceful reload.
"""

import json
import os
import shutil
import subprocess
import threading
from datetime import datetime
from http.server import HTTPServer, BaseHTTPRequestHandler
from string import Template
from pathlib import Path
from typing import Optional
import signal
import sys

# Configuration
NGINX_CONF_PATH = Path(os.environ.get('NGINX_DYNAMIC_CONF_PATH', '/etc/nginx/conf.d/dynamic_backends.conf'))
ROUTES_DB_PATH = Path(os.environ.get('ROUTES_DB_PATH', '/var/lib/nginx-api/routes.json'))
BACKUP_DIR = Path(os.environ.get('NGINX_BACKUP_DIR', '/var/backups/nginx'))
API_PORT = int(os.environ.get('NGINX_CONFIG_API_PORT', '8081'))

# Thread lock for config operations
config_lock = threading.Lock()

# Nginx config template using string.Template (stdlib)
NGINX_TEMPLATE = Template("""# Auto-generated by nginx-config-api
# Last updated: $timestamp
# DO NOT EDIT MANUALLY - changes will be overwritten

$upstream_blocks

# Dynamic server block for backend proxying
server {
    listen 8090;
    server_name _;

    # Access log for dynamic backends
    access_log /dev/stdout main;

$location_blocks

    # Default fallback for unconfigured routes
    location / {
        return 404 '{"error": "no route configured for this path"}';
        default_type application/json;
    }
}
""")

UPSTREAM_TEMPLATE = Template("""upstream $upstream_name {
    least_conn;
$servers
    keepalive 32;
}
""")

LOCATION_TEMPLATE = Template("""    location $path {
        proxy_pass http://$upstream_name;
        proxy_http_version 1.1;
        proxy_set_header Host $$host;
        proxy_set_header X-Real-IP $$remote_addr;
        proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $$scheme;
        proxy_set_header Connection "";
        proxy_connect_timeout ${connect_timeout}s;
        proxy_read_timeout ${read_timeout}s;
        proxy_send_timeout ${send_timeout}s;
        proxy_buffering on;
        proxy_buffer_size 4k;
        proxy_buffers 8 4k;
    }
""")

# Empty config template when no routes defined
EMPTY_CONFIG_TEMPLATE = """# Auto-generated by nginx-config-api
# Last updated: {timestamp}
# No routes configured yet

# Placeholder server to keep nginx happy
server {{
    listen 8090;
    server_name _;

    location / {{
        return 503 '{{"error": "no backends configured"}}';
        default_type application/json;
    }}
}}
"""


class RouteStore:
    """Persistent storage for route configurations."""

    def __init__(self, db_path: Path):
        self.db_path = db_path
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._load()

    def _load(self):
        if self.db_path.exists():
            try:
                with open(self.db_path) as f:
                    self.routes = json.load(f)
            except json.JSONDecodeError:
                print(f"Warning: Could not parse {self.db_path}, starting fresh")
                self.routes = {}
        else:
            self.routes = {}

    def _save(self):
        tmp_path = self.db_path.with_suffix('.tmp')
        with open(tmp_path, 'w') as f:
            json.dump(self.routes, f, indent=2)
        tmp_path.rename(self.db_path)  # Atomic on POSIX

    def get_all(self) -> dict:
        return self.routes.copy()

    def get(self, path: str) -> Optional[dict]:
        return self.routes.get(path)

    def set(self, path: str, backends: list, options: dict = None):
        """
        Set backends for a path.
        backends: [{"address": "10.0.0.1", "port": 8080, "weight": 1}, ...]
        options: {"connect_timeout": 5, "read_timeout": 60, "send_timeout": 60}
        """
        self.routes[path] = {
            "backends": backends,
            "options": options or {},
            "created_at": self.routes.get(path, {}).get("created_at", datetime.now().isoformat()),
            "updated_at": datetime.now().isoformat()
        }
        self._save()

    def delete(self, path: str) -> bool:
        if path in self.routes:
            del self.routes[path]
            self._save()
            return True
        return False

    def clear(self):
        """Remove all routes."""
        self.routes = {}
        self._save()


class NginxConfigGenerator:
    """Generates and applies nginx configuration."""

    def __init__(self, store: RouteStore, conf_path: Path, backup_dir: Path):
        self.store = store
        self.conf_path = conf_path
        self.backup_dir = backup_dir
        self.backup_dir.mkdir(parents=True, exist_ok=True)
        self.conf_path.parent.mkdir(parents=True, exist_ok=True)

    def _path_to_upstream_name(self, path: str) -> str:
        """Convert path to valid upstream name."""
        # Remove leading/trailing slashes, replace special chars
        name = path.strip('/').replace('/', '_').replace('-', '_').replace('.', '_')
        # Ensure valid identifier
        name = ''.join(c if c.isalnum() or c == '_' else '_' for c in name)
        return f"backend_{name}" if name else "backend_root"

    def generate_config(self) -> str:
        """Generate complete nginx config from current routes."""
        routes = self.store.get_all()

        if not routes:
            return EMPTY_CONFIG_TEMPLATE.format(timestamp=datetime.now().isoformat())

        upstream_blocks = []
        location_blocks = []

        # Sort paths by length (longest first) for correct nginx matching
        sorted_paths = sorted(routes.keys(), key=len, reverse=True)

        for path in sorted_paths:
            route_data = routes[path]
            upstream_name = self._path_to_upstream_name(path)

            # Build server list
            servers = []
            for backend in route_data["backends"]:
                server_line = f"    server {backend['address']}:{backend['port']}"
                if backend.get("weight", 1) != 1:
                    server_line += f" weight={backend['weight']}"
                if backend.get("max_fails"):
                    server_line += f" max_fails={backend['max_fails']}"
                if backend.get("fail_timeout"):
                    server_line += f" fail_timeout={backend['fail_timeout']}s"
                if backend.get("backup"):
                    server_line += " backup"
                if backend.get("down"):
                    server_line += " down"
                server_line += ";"
                servers.append(server_line)

            upstream_blocks.append(UPSTREAM_TEMPLATE.substitute(
                upstream_name=upstream_name,
                servers='\n'.join(servers)
            ))

            # Get timeout options with defaults
            options = route_data.get("options", {})
            location_blocks.append(LOCATION_TEMPLATE.substitute(
                path=path,
                upstream_name=upstream_name,
                connect_timeout=options.get("connect_timeout", 5),
                read_timeout=options.get("read_timeout", 60),
                send_timeout=options.get("send_timeout", 60)
            ))

        return NGINX_TEMPLATE.substitute(
            timestamp=datetime.now().isoformat(),
            upstream_blocks='\n'.join(upstream_blocks),
            location_blocks='\n'.join(location_blocks)
        )

    def validate_config(self, config_content: str) -> tuple:
        """Validate nginx config without applying."""
        # Write to temp file
        tmp_path = self.conf_path.with_suffix('.tmp')
        tmp_path.write_text(config_content)

        try:
            result = subprocess.run(
                ['nginx', '-t'],
                capture_output=True,
                text=True,
                timeout=10
            )
            return result.returncode == 0, result.stderr
        except subprocess.TimeoutExpired:
            return False, "Validation timed out"
        except FileNotFoundError:
            return False, "nginx binary not found"
        finally:
            tmp_path.unlink(missing_ok=True)

    def apply_config(self, skip_reload: bool = False) -> dict:
        """Generate, validate, backup, and apply new config."""
        config_content = self.generate_config()

        # Validate first
        valid, error = self.validate_config(config_content)
        if not valid:
            return {"success": False, "error": f"Validation failed: {error}"}

        # Backup current config
        backup_path = None
        if self.conf_path.exists():
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            backup_path = self.backup_dir / f"dynamic_backends.{timestamp}.conf"
            shutil.copy2(self.conf_path, backup_path)

        # Write new config atomically
        tmp_path = self.conf_path.with_suffix('.tmp')
        tmp_path.write_text(config_content)
        tmp_path.rename(self.conf_path)

        if skip_reload:
            return {
                "success": True,
                "backup": str(backup_path) if backup_path else None,
                "routes_count": len(self.store.get_all()),
                "reloaded": False
            }

        # Reload nginx
        try:
            result = subprocess.run(
                ['nginx', '-s', 'reload'],
                capture_output=True,
                text=True,
                timeout=10
            )
            if result.returncode != 0:
                # Rollback
                if backup_path and backup_path.exists():
                    shutil.copy2(backup_path, self.conf_path)
                    subprocess.run(['nginx', '-s', 'reload'], timeout=10)
                return {"success": False, "error": f"Reload failed: {result.stderr}"}
        except Exception as e:
            return {"success": False, "error": str(e)}

        return {
            "success": True,
            "backup": str(backup_path) if backup_path else None,
            "routes_count": len(self.store.get_all()),
            "reloaded": True
        }

    def rollback(self, backup_file: str) -> dict:
        """Rollback to a specific backup."""
        backup_path = Path(backup_file)
        if not backup_path.exists():
            # Try looking in backup dir
            backup_path = self.backup_dir / backup_file

        if not backup_path.exists():
            return {"success": False, "error": "Backup file not found"}

        try:
            shutil.copy2(backup_path, self.conf_path)
            result = subprocess.run(
                ['nginx', '-s', 'reload'],
                capture_output=True,
                text=True,
                timeout=10
            )
            if result.returncode != 0:
                return {"success": False, "error": f"Reload failed: {result.stderr}"}
            return {"success": True, "restored_from": str(backup_path)}
        except Exception as e:
            return {"success": False, "error": str(e)}

    def list_backups(self) -> list:
        """List available backup files."""
        backups = []
        for f in sorted(self.backup_dir.glob("*.conf"), reverse=True):
            stat = f.stat()
            backups.append({
                "filename": f.name,
                "path": str(f),
                "size": stat.st_size,
                "modified": datetime.fromtimestamp(stat.st_mtime).isoformat()
            })
        return backups


class ConfigAPIHandler(BaseHTTPRequestHandler):
    """HTTP request handler for the config API."""

    store: RouteStore = None
    generator: NginxConfigGenerator = None

    def send_json(self, status: int, data: dict):
        self.send_response(status)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()
        self.wfile.write(json.dumps(data, indent=2).encode())

    def read_json(self) -> Optional[dict]:
        content_length = int(self.headers.get('Content-Length', 0))
        if content_length == 0:
            return None
        body = self.rfile.read(content_length)
        return json.loads(body.decode())

    def do_OPTIONS(self):
        """Handle CORS preflight."""
        self.send_response(204)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()

    def do_GET(self):
        if self.path == '/routes':
            # List all routes
            routes = self.store.get_all()
            self.send_json(200, {"routes": routes, "count": len(routes)})

        elif self.path.startswith('/routes/'):
            # Get specific route
            route_path = self.path[7:]  # Remove '/routes'
            route = self.store.get(route_path)
            if route:
                self.send_json(200, {"path": route_path, **route})
            else:
                self.send_json(404, {"error": "Route not found"})

        elif self.path == '/config/preview':
            # Preview generated config without applying
            config = self.generator.generate_config()
            self.send_json(200, {"config": config})

        elif self.path == '/config/backups':
            # List available backups
            backups = self.generator.list_backups()
            self.send_json(200, {"backups": backups, "count": len(backups)})

        elif self.path == '/health':
            self.send_json(200, {
                "status": "healthy",
                "service": "nginx-config-api",
                "routes_count": len(self.store.get_all())
            })

        elif self.path == '/':
            # API info
            self.send_json(200, {
                "service": "nginx-config-api",
                "version": "1.0.0",
                "endpoints": {
                    "GET /routes": "List all routes",
                    "GET /routes/<path>": "Get specific route",
                    "POST /routes": "Add/update route",
                    "DELETE /routes/<path>": "Delete route",
                    "DELETE /routes": "Delete all routes",
                    "GET /config/preview": "Preview nginx config",
                    "POST /config/reload": "Force reload",
                    "GET /config/backups": "List backups",
                    "POST /config/rollback": "Rollback to backup",
                    "GET /health": "Health check"
                }
            })

        else:
            self.send_json(404, {"error": "Not found"})

    def do_POST(self):
        if self.path == '/routes':
            # Add/update a route
            try:
                data = self.read_json()
                if not data or 'path' not in data or 'backends' not in data:
                    self.send_json(400, {"error": "Missing 'path' or 'backends'"})
                    return

                # Validate path format
                if not data['path'].startswith('/'):
                    self.send_json(400, {"error": "Path must start with '/'"})
                    return

                # Validate backends structure
                for b in data['backends']:
                    if 'address' not in b or 'port' not in b:
                        self.send_json(400, {"error": "Backend needs 'address' and 'port'"})
                        return
                    if not isinstance(b['port'], int) or b['port'] < 1 or b['port'] > 65535:
                        self.send_json(400, {"error": "Backend port must be 1-65535"})
                        return

                with config_lock:
                    self.store.set(
                        data['path'],
                        data['backends'],
                        data.get('options')
                    )
                    result = self.generator.apply_config()

                if result['success']:
                    self.send_json(200, {"message": "Route added/updated", **result})
                else:
                    self.send_json(500, result)

            except json.JSONDecodeError:
                self.send_json(400, {"error": "Invalid JSON"})

        elif self.path == '/routes/batch':
            # Add/update multiple routes at once
            try:
                data = self.read_json()
                if not data or 'routes' not in data:
                    self.send_json(400, {"error": "Missing 'routes' array"})
                    return

                with config_lock:
                    for route in data['routes']:
                        if 'path' in route and 'backends' in route:
                            self.store.set(
                                route['path'],
                                route['backends'],
                                route.get('options')
                            )
                    result = self.generator.apply_config()

                if result['success']:
                    self.send_json(200, {"message": f"Batch update complete", **result})
                else:
                    self.send_json(500, result)

            except json.JSONDecodeError:
                self.send_json(400, {"error": "Invalid JSON"})

        elif self.path == '/config/reload':
            # Force reload without changes
            with config_lock:
                result = self.generator.apply_config()
            status = 200 if result['success'] else 500
            self.send_json(status, result)

        elif self.path == '/config/rollback':
            try:
                data = self.read_json()
                if not data or 'backup' not in data:
                    self.send_json(400, {"error": "Missing 'backup' filename"})
                    return

                with config_lock:
                    result = self.generator.rollback(data['backup'])
                status = 200 if result['success'] else 500
                self.send_json(status, result)

            except json.JSONDecodeError:
                self.send_json(400, {"error": "Invalid JSON"})

        else:
            self.send_json(404, {"error": "Not found"})

    def do_PUT(self):
        """Alias for POST on routes."""
        if self.path == '/routes' or self.path == '/routes/batch':
            self.do_POST()
        else:
            self.send_json(404, {"error": "Not found"})

    def do_DELETE(self):
        if self.path == '/routes':
            # Delete all routes
            with config_lock:
                self.store.clear()
                result = self.generator.apply_config()
            if result['success']:
                self.send_json(200, {"message": "All routes deleted", **result})
            else:
                self.send_json(500, result)

        elif self.path.startswith('/routes/'):
            route_path = self.path[7:]
            with config_lock:
                if self.store.delete(route_path):
                    result = self.generator.apply_config()
                    if result['success']:
                        self.send_json(200, {"message": "Route deleted", **result})
                    else:
                        self.send_json(500, result)
                else:
                    self.send_json(404, {"error": "Route not found"})
        else:
            self.send_json(404, {"error": "Not found"})

    def log_message(self, format, *args):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        print(f"[{timestamp}] [config-api] {args[0]}")


def run_server(port: int):
    """Start the API server."""
    store = RouteStore(ROUTES_DB_PATH)
    generator = NginxConfigGenerator(store, NGINX_CONF_PATH, BACKUP_DIR)

    # Inject dependencies into handler
    ConfigAPIHandler.store = store
    ConfigAPIHandler.generator = generator

    # Create initial empty config if none exists
    if not NGINX_CONF_PATH.exists():
        print("Creating initial dynamic config...")
        result = generator.apply_config(skip_reload=True)
        print(f"Initial config: {result}")
    elif store.get_all():
        print("Applying existing routes on startup...")
        result = generator.apply_config(skip_reload=True)
        print(f"Startup apply: {result}")

    server = HTTPServer(('0.0.0.0', port), ConfigAPIHandler)

    def shutdown(signum, frame):
        print("\nShutting down config API...")
        server.shutdown()
        sys.exit(0)

    signal.signal(signal.SIGINT, shutdown)
    signal.signal(signal.SIGTERM, shutdown)

    print(f"[config-api] Nginx Config API running on port {port}")
    print("[config-api] Endpoints:")
    print("  GET    /                - API info")
    print("  GET    /routes          - List all routes")
    print("  GET    /routes/<path>   - Get specific route")
    print("  POST   /routes          - Add/update route")
    print("  POST   /routes/batch    - Batch add/update routes")
    print("  DELETE /routes/<path>   - Delete route")
    print("  DELETE /routes          - Delete all routes")
    print("  GET    /config/preview  - Preview nginx config")
    print("  GET    /config/backups  - List backups")
    print("  POST   /config/reload   - Force reload")
    print("  POST   /config/rollback - Rollback to backup")
    print("  GET    /health          - Health check")

    server.serve_forever()


if __name__ == '__main__':
    run_server(API_PORT)
